[project]
name = "pySpeechModule"
version = "1.0.1"
authors = [
  { name="John Settlemyer", email="author@example.com" },
]
dependencies = [
  "soundfile>=0.14.0",
]
description = "A framework for creating speechd modules"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/jsett/py-speech-module"
Issues = "https://github.com/jsett/py-speech-module/issues"